#!/usr/bin/env python

import rospy

import actionlib
from move_base_msgs.msg import MoveBaseAction, MoveBaseGoal
from simple_navigation_goals.srv import *

def movebase_client(req):

    client = actionlib.SimpleActionClient('move_base',MoveBaseAction)
    client.wait_for_server()

    goal = MoveBaseGoal()
    goal.target_pose.header.frame_id = "map"
    goal.target_pose.header.stamp = rospy.Time.now()
    goal.target_pose.pose.position.x = req.x
    goal.target_pose.pose.position.y = req.y
    goal.target_pose.pose.orientation.z = req.z
    goal.target_pose.pose.orientation.w = req.w

    client.send_goal(goal)
    wait = client.wait_for_result()
    if not wait:
        rospy.logerr("Action server not available!")
        rospy.signal_shutdown("Action server not available!")
    else:
        return simple_navigation_goalsResponse(1)

def move_base_server():
        rospy.init_node('movebase_client_server')
        s = rospy.Service('simple_navigation_golas', simple_navigation_goals, movebase_client)
	print("Ready to recieve goals")
	rospy.spin()   	

if __name__ == '__main__':
	move_base_server()
